class Klass
attr_accessor :counter

def initialize(c)
  @counter= c
end

def plus
  self.counter = self.counter+ 1
end
end
---------------------------  

rollbacker.perform(Klass.new(0)) {|k| k.plus} //this leaves the counter in 1. Currently working fine

---------------------------
k = Klass.new(0)
def kaboom(k)
  tr.perform(k) {|k|
    k.plus
    raise 'Kaboom!'}
end                    //This should raise the error (which it does), but the counter should stay on 0; but at the moment it stays in 1 (the plus happens, but not rollback is happening)
